<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.2040" tests="12" failures="6">
  <testsuite name="Root Suite" timestamp="2022-12-26T12:51:45" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="reminders_api" timestamp="2022-12-26T12:51:45" tests="12" file="/projects/challenge/test/index.spec.js" time="0.2040" failures="6">
    <testcase name="reminders_api should create a new reminder" time="0.0390" classname="should create a new reminder">
    </testcase>
    <testcase name="reminders_api should fetch all the reminders" time="0.0270" classname="should fetch all the reminders">
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present for user" time="0.0220" classname="should fetch no reminders if no matching results are present for user">
    </testcase>
    <testcase name="reminders_api should fetch no reminders if no matching results are present after the date" time="0.0190" classname="should fetch no reminders if no matching results are present after the date">
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user" time="0.0150" classname="should fetch all the reminders for a user">
    </testcase>
    <testcase name="reminders_api should fetch all the reminders after the date" time="0.0170" classname="should fetch all the reminders after the date">
      <failure message="expected [] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:94:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch all the reminders for a user after the date" time="0.0160" classname="should fetch all the reminders for a user after the date">
      <failure message="expected [] to deeply equal [ Array(1) ]" type="AssertionError"><![CDATA[AssertionError: expected [] to deeply equal [ Array(1) ]
    at Context.<anonymous> (test/index.spec.js:101:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should fetch a single reminder" time="0.0070" classname="should fetch a single reminder">
    </testcase>
    <testcase name="reminders_api should get 404 if the reminder ID does not exist" time="0.0090" classname="should get 404 if the reminder ID does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200
    at Context.<anonymous> (test/index.spec.js:114:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a put request to /reminders/:id" time="0.0110" classname="should get 405 for a put request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:122:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a patch request to /reminders/:id" time="0.0110" classname="should get 405 for a patch request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:128:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
    <testcase name="reminders_api should get 405 for a delete request to /reminders/:id" time="0.0110" classname="should get 405 for a delete request to /reminders/:id">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 405 but got 404
    at Context.<anonymous> (test/index.spec.js:134:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>